V4.1 dev
donaldzou/WGDashboard pull request #484
Opened 2024-11-12 18:21 UTC by DaanSelen

The new PR!
https://github.com/jpizquierdo
https://github.com/TheSL18

2024-11-12 18:24 UTC, DaanSelen commented on src/static/locale/active_languages.json
Can you make it Alphabetical? Then we can Merge!

2024-11-12 18:24 UTC, DaanSelen commented on src/static/locale/active_languages.json
Make sure to keep capitalization like the others :)

2024-11-13 13:26 UTC, jpizquierdo commented
Thanks, i think that you forgot to mention is with de "@", so I have just read because I ipen the repo :)

 @TheSL18 , just to let you know

2024-11-13 13:29 UTC, DaanSelen commented
> Thanks, i think that you forgot to mention is with de "@", so I have just read because I ipen the repo :)
> 
> @TheSL18 , just to let you know that there are some small fixes to make in @DaanSelen comments

Thanks! Once those are ironed out and you approve, we can merge into 4.2

2024-11-13 16:34 UTC, jpizquierdo approved these changes

2024-11-13 16:45 UTC, jpizquierdo requested changes
there are some fixes needed, commented in the lines affected

2024-11-13 16:45 UTC, jpizquierdo commented on src/static/locale/active_languages.json
> +  {
italian is duplicated, the second one seem to be needed to remove

2024-11-13 16:45 UTC, jpizquierdo commented on src/static/locale/active_languages.json
> +  {
"uk" goes after "ru"

2024-11-13 16:51 UTC, closed without merging

2024-11-13 18:14 UTC, DaanSelen commented
You can always provide additions to the Spanish or other translations!