Added template and script to check local files
donaldzou/WGDashboard pull request #488
Opened 2024-11-13 18:03 UTC by donaldzou

# How to use

`python3 verify_locale_files.py ` in `src/static/locale`

## Example

```
(venv) donaldzou@Mac locale % python3 verify_locale_files.py 
========================================================
| WGDashboard Locale File Verification [by @donaldzou] |
========================================================

Active Languages
        [Language #1] Czech
        [Language #2] German
        [Language #3] English
        [Language #4] Italian
        [Language #5] Dutch
        [Language #6] Russian
        [Language #7] Turkish
        [Language #8] Ukrainian
        [Language #9] Chinese (Simplified)
        [Language #10] Chinese (Traditional)
Select the language number you want to verify or enter [q] to exit: 1

Selected Language: Czech

        [Missing Translations] Simply copy the JSON below into the locale file and translate them in :)
                "Signing In\.\.\.": "",
                "Multi-Factor Authentication \(MFA\)": "",
                "Are you sure to delete this API key\?": "",
                "When should this API Key expire\?": "",
                "Creating\.\.\.": "",
                "Turning On\.\.\.": "",
                "Turning Off\.\.\.": "",
                "Search Peers\.\.\.": "",
                "\(Required for QR Code and Download\)": "",
                "\(Required\)": "",
                "This peer does not have any job yet\.": "",
                "No active job at the moment\.": "",
                "Sharing\.\.\.": "",
                "Stop Sharing\.\.\.": "",
                "Restricting\.\.\.": "",
                "Allowing Access\.\.\.": "",
                "Download \& QR Code is not available due to no private key set for this peer": "",
                "By adding peers by bulk, each peer's name will be auto generated, and Allowed IP will be assign to the next available IP\.": "",
                "How many peers you want to add\?": "",
                "Adding\.\.\.": "",
                "Dashboard IP Address \& Listen Port": ""

        [Deprecated Translations] Simply remove the translation below :)1
                "Signing In...": "Přihlašování..."
                "Multi-Factor Authentication (MFA)": "Vícefaktorové ověření (MFA)"
                "Are you sure to delete this API key?": "Určitě chcete smazat tento API klíč?"
                "When should this API Key expire?": "Kdy má tento API klíč vypršet?"
                "Creating...": "Tvořím..."
                "Turning On...": "Zapínám..."
                "Turning Off...": "Vypínám..."
                "Search Peers...": "Hledat peers..."
                "(Required for QR Code and Download)": "(Nutné pro QR kód a stažení)"
                "(Required)": "(Povinné)"
                "This peer does not have any job yet.": "Tento peer ještě nemá žádný úkol."
                "No active job at the moment.": "Žádný úkol v současnosti neprobíhá."
                "Sharing...": "Sdílím..."
                "Stop Sharing...": "Ukončit sdílení..."
                "Restricting...": "Omezuji..."
                "Allowing Access...": "Povoluji přístup..."
                "Download & QR Code is not available due to no private key set for this peer": "Stažení a QR kód nejsou k dispozici, peer nemá nastavený soukromý klíč."
                "By adding peers by bulk, each peer's name will be auto generated, and Allowed IP will be assign to the next available IP.": "Při hromadném importu bude jméno každého peera vygenerované automaticky, a povolená IP adresa bude nastavena na další v pořadí"
                "How many peers you want to add?": "Kolik peerů chcete přidat?"
                "Adding...": "Přidávám..."
```

2024-11-13 18:04 UTC, donaldzou commented
Hi @DaanSelen, when u are free, do you mind going through this PR and see if there's anything to improve and streamline the localization process?

Thank u!

2024-11-13 18:12 UTC, DaanSelen commented
I'll go through it, give me some time!

2024-11-14 20:41 UTC, DaanSelen commented
https://github.com/donaldzou/WGDashboard/pull/492

2024-11-16 12:36 UTC, DaanSelen requested changes
Couple points:
I don't think the PL is alphabetical behind the ZH-HK?
The indentation in `pl-pl.json` is not consistent. (content looks good)
The Dutch translation changed `...` to `\\.\\.\\.`

2024-11-16 13:07 UTC, DaanSelen commented on src/static/locale/nl-nl.json
> +  "Signing In\\.\\.\\.": "Inloggen...",
Which one is leading?

2024-11-16 13:07 UTC, DaanSelen commented on src/static/locale/pl.json
> +    "Backup not selected": "Nie wybrano kopii zapasowej",
Indentation looks to be forgotten.

2024-11-16 13:07 UTC, DaanSelen commented on src/static/locale/uk.json
> +	"Dashboard IP Address \\& Listen Port": "",
Empty line in Ukranian.

2024-11-16 17:00 UTC, donaldzou commented
Yes I found out a bug in the python script that it escaped 2 back slashes when printed out. Need to figure that out :)

2024-11-18 08:14 UTC, DaanSelen commented
> Yes I found out a bug in the python script that it escaped 2 back slashes when printed out. Need to figure that out :)

Did all things get resolved?

2024-11-21 17:49 UTC, donaldzou commented
> > Yes I found out a bug in the python script that it escaped 2 back slashes when printed out. Need to figure that out :)
> 
> Did all things get resolved?

Yes, now what's left to do is fixing the empty translations that got replaced by the regex escaped keys:

"Sharing..." ==> "Sharing\\.\\.\\."

2024-11-21 17:49 UTC, donaldzou commented
The current script will insert the new translation and remove deprecated ones directly from the file.

2024-11-21 19:31 UTC, DaanSelen approved these changes

2024-11-23 07:18 UTC, merged