French translation
donaldzou/WGDashboard pull request #549
Opened 2024-12-08 02:33 UTC by alexperreault

Bonjour!

I translated the app in French.

Thanks!

2024-12-08 05:04 UTC, donaldzou commented
Merci beaucoup! (I hope my high school French is correct haha)

Will go over it later and will merge it to the main branch if everything is good ;)

2025-01-02 09:20 UTC, DaanSelen requested changes
Looks good!

2025-01-02 09:20 UTC, DaanSelen commented on src/static/locale/active_languages.json
> +	},
Can this be placed in alphabetical order?

2025-01-03 01:12 UTC, alexperreault commented on src/static/locale/active_languages.json
> +	},
done

2025-01-03 07:38 UTC, DaanSelen approved these changes

2025-01-03 07:39 UTC, merged

2025-01-03 07:42 UTC, DaanSelen commented
@alexperreault Thanks for your work! I/we appreciate it, you can view it by doing a ./wgd.sh update or repull and run the container.