ajout french language
donaldzou/WGDashboard pull request #561
Opened 2024-12-25 21:42 UTC by mgrafr

language french checked with 'verify_locale_files.py'

2025-01-02 09:22 UTC, DaanSelen commented
Hello @mgrafr did you use: https://github.com/donaldzou/WGDashboard/pull/549
Or a completely different French translation?

2025-01-02 09:22 UTC, DaanSelen requested changes
Looks great!

2025-01-02 09:22 UTC, DaanSelen commented on src/static/locale/active_languages.json
> +                "lang_name": "french",
Can you make this alphabetical?

2025-01-03 01:07 UTC, alexperreault commented on src/static/locale/fr-fr.json
> +	"Setup": "nstallation",
Typo
"Installation"

2025-01-03 01:08 UTC, alexperreault commented
> Hello @mgrafr did you use: #549 Or a completely different French translation?

Seems to be different from mine (#549), plus this is Fr-fr, I did Fr-CA

2025-01-03 07:34 UTC, DaanSelen commented
> > Hello @mgrafr did you use: #549 Or a completely different French translation?
> 
> Seems to be different from mine (#549), plus this is Fr-fr, I did Fr-CA

Thanks, We'll keep that in mind

2025-01-03 07:35 UTC, DaanSelen commented on src/static/locale/active_languages.json
> +                "lang_name": "french",
And capitalize

2025-01-03 08:05 UTC, mgrafr commented
Good morning 
I discovered Alexandre Perreault's PR only after creating mine.
I carried out the translation using the terms that I wanted to appear in the application also apart from some very English that we use in France (QR code for ca and QR code for fr, for example the differences should be minimal.
So just call the fr-CA translation fr.json (like for uk.json) and it will be the translation for the French language.

2025-01-03 08:07 UTC, DaanSelen commented
> Good morning I discovered Alexandre Perreault's PR only after creating mine. I carried out the translation using the terms that I wanted to appear in the application also apart from some very English that we use in France (QR code for ca and QR code for fr, for example the differences should be minimal. So just call the fr-CA translation fr.json (like for uk.json) and it will be the translation for the French language.

Good morning.
Would you be willing to update your branch and look through the changes and give it the general ISO name? If you both agree on that, it has been a long while since I have refreshed my French.

2025-01-06 12:39 UTC, DaanSelen commented
@mgrafr @alexperreault since you both added french, can we perhaps close this PR and you can together (in this discussion maybe) agree to the state of the French translation?

2025-01-06 17:27 UTC, alexperreault commented
Our translations should be (and seem to be) pretty similar. I don't mind mine becoming the generic french translation.

Waiting on @mgrafr 's opinion

2025-01-08 14:11 UTC, mgrafr commented
everything is settled, @alexperreault's translation becomes the generic French translation

2025-01-09 06:05 UTC, donaldzou commented
Will close this now :) Thanks you all for the hard work!

2025-02-06 11:48 UTC, DaanSelen commented
> Will close this now :) Thanks you all for the hard work!

You forgot to close x)

2025-02-06 11:48 UTC, closed without merging